import {
  REACT_APP_ETHERSCAN_API_KEY,
  REACT_APP_INFURA_PROJECT_ID,
  REACT_APP_NETWORK,
  REACT_APP_ETHPLORER_API_KEY,
  REACT_APP_ADDRESS,
  REACT_APP_AFFILIATE_FEE,
} from '@env';

export const ETHERSCAN_API_KEY = REACT_APP_ETHERSCAN_API_KEY;
export const INFURA_PROJECT_ID = REACT_APP_INFURA_PROJECT_ID || '';

export const NETWORK_TYPE = REACT_APP_NETWORK || 'mainnet';

export const ETHPLORER_API_KEY = REACT_APP_ETHPLORER_API_KEY;
export const ADDRESS = REACT_APP_ADDRESS;

const AFFILIATE: number = parseFloat(REACT_APP_AFFILIATE_FEE || '');
export const AFFILIATE_FEE: number =
  AFFILIATE > 0 && AFFILIATE <= 0.1 ? AFFILIATE : 0;
